# NumPy Intro


In [2]:
import numpy as np

a = np.arange(15).reshape(3,5)

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int64'

In [6]:
a.size

15

In [7]:
a.itemsize

8

In [8]:
type(a)

numpy.ndarray

### Create an array

In [10]:
b = np.array([1,2,3,4,5])

b
b.dtype

dtype('int64')

### create complex type

In [12]:
c = np.array([[1,2],[3,4]],dtype=complex)

c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

### basic operation

In [14]:
a = np.array([10,20,30,40])

b = np.arange(4)

c = a-b

c

array([10, 19, 28, 37])

In [15]:
a < 11

array([ True, False, False, False])

In [19]:
A = np.array([[2,3],[5,6]])
B = np.array([[1, 2], [3, 4]])

#A * B   # element-wise multiplication
#A.dot(B) # matrix multiplication
# A @ B # matrix multiplication

A.T

array([[2, 5],
       [3, 6]])